<a href="https://colab.research.google.com/github/MalyarAnastasia/AI-Engineering/blob/main/homeworks/HW01/HW01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np

In [18]:
a = np.array([1, 5, 10])
a.shape

[[3 8 2]
 [9 6 2]]


In [20]:
b = np.array([[3, 8, 2], [9, 6, 2]])
print(b)
np.shape(b)

[[3 8 2]
 [9 6 2]]


(2, 3)

In [27]:
a = np.ones((2, 6, 5))
a

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [28]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
a = np.arange(3, 10, 2)
a

array([3, 5, 7, 9])

In [49]:
a = np.array([[3, 0, 2], [9, 5, 9]])
b = ([[5, 6, 3], [5, 10, 25]])
a+b

array([[ 8,  6,  5],
       [14, 15, 34]])

In [50]:
a/b

array([[0.6       , 0.        , 0.66666667],
       [1.8       , 0.5       , 0.36      ]])

In [51]:
a*16

array([[ 48,   0,  32],
       [144,  80, 144]])

In [53]:
d = np.transpose(a*16)
d

array([[ 48, 144],
       [  0,  80],
       [ 32, 144]])

In [69]:
e = np.ones((2, 3))
e = np.cos(e)
e

array([[0.54030231, 0.54030231, 0.54030231],
       [0.54030231, 0.54030231, 0.54030231]])

In [70]:
np.round(e, 2)

array([[0.54, 0.54, 0.54],
       [0.54, 0.54, 0.54]])

In [76]:
print(a)
np.sum(a)

[[3 0 2]
 [9 5 9]]


np.int64(28)

In [129]:
a = np.array([[3, 6, 10], [8, 2, 9], [5, 8, 3]])
a

array([[ 3,  6, 10],
       [ 8,  2,  9],
       [ 5,  8,  3]])

In [131]:
a[0,0]

np.int64(3)

In [133]:
a[0,2] = 0
a

array([[3, 6, 0],
       [8, 2, 9],
       [5, 8, 3]])

In [136]:
b = np.array(([[4, 7, 2], [9, 5, 8]], [[9, 40, 4], [6, 8, 3]]))
b.shape

(2, 2, 3)

In [141]:
b.ravel()

array([ 4,  7,  2,  9,  5,  8,  9, 40,  4,  6,  8,  3])

In [143]:
c = b.view()
c

array([[[ 4,  7,  2],
        [ 9,  5,  8]],

       [[ 9, 40,  4],
        [ 6,  8,  3]]])