<a href="https://colab.research.google.com/github/MalyarAnastasia/AI-Engineering/blob/main/homeworks/HWO1/HW01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([1, 5, 10])
a.shape

(3,)

In [22]:
b = np.array([[3, 8, 2], [9, 6, 2]])
print(b)
np.shape(b)

[[3 8 2]
 [9 6 2]]


(2, 3)

In [4]:
a = np.ones((2, 6, 5))
a

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [5]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
a = np.arange(3, 10, 2)
a

array([3, 5, 7, 9])

In [7]:
a = np.array([[3, 0, 2], [9, 5, 9]])
b = ([[5, 6, 3], [5, 10, 25]])
a+b

array([[ 8,  6,  5],
       [14, 15, 34]])

In [8]:
a/b

array([[0.6       , 0.        , 0.66666667],
       [1.8       , 0.5       , 0.36      ]])

In [9]:
a*16

array([[ 48,   0,  32],
       [144,  80, 144]])

In [10]:
d = np.transpose(a*16)
d

array([[ 48, 144],
       [  0,  80],
       [ 32, 144]])

In [11]:
e = np.ones((2, 3))
e = np.cos(e)
e

array([[0.54030231, 0.54030231, 0.54030231],
       [0.54030231, 0.54030231, 0.54030231]])

In [12]:
np.round(e, 2)

array([[0.54, 0.54, 0.54],
       [0.54, 0.54, 0.54]])

In [13]:
print(a)
np.sum(a)

[[3 0 2]
 [9 5 9]]


np.int64(28)

In [24]:
a = np.array([[3, 6, 10], [8, 2, 9], [5, 8, 3]])
a

array([[ 3,  6, 10],
       [ 8,  2,  9],
       [ 5,  8,  3]])

In [15]:
a[0,0]

np.int64(3)

In [16]:
a[0,2] = 0
a

array([[3, 6, 0],
       [8, 2, 9],
       [5, 8, 3]])

In [26]:
a[3:5]

array([], shape=(0, 3), dtype=int64)

In [27]:
a[::-1]

array([[ 5,  8,  3],
       [ 8,  2,  9],
       [ 3,  6, 10]])

In [28]:
b = np.array([[ 6,  4,  2,  3],
              [17, 31, 95, 68],
              [67, 26, 95, 23],
              [8, 3, 75, 1],
              [4, 9, 23, 0]])
b

array([[ 6,  4,  2,  3],
       [17, 31, 95, 68],
       [67, 26, 95, 23],
       [ 8,  3, 75,  1],
       [ 4,  9, 23,  0]])

In [29]:
b[(2,3)]

np.int64(23)

In [31]:
b[[2,3]]

array([[67, 26, 95, 23],
       [ 8,  3, 75,  1]])

In [32]:
b[:,3]

array([ 3, 68, 23,  1,  0])

In [17]:
b = np.array(([[4, 7, 2], [9, 5, 8]], [[9, 40, 4], [6, 8, 3]]))
b.shape

(2, 2, 3)

In [18]:
b.ravel()

array([ 4,  7,  2,  9,  5,  8,  9, 40,  4,  6,  8,  3])

In [38]:
c = b.view()
c


array([[ 6,  4,  2,  3],
       [17, 31, 95, 68],
       [67, 26, 95, 23],
       [ 8,  3, 75,  1],
       [ 4,  9, 23,  0]])

In [44]:
print("dtype:", c.dtype)
print("Вычисление средней величины", c.mean())
print("Минимальное число", c.min())
print("Максимальное число", c.max())

dtype: int64
Вычисление средней величины 28.0
Минимальное число 0
Максимальное число 95
